// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index_bak from "./routes/index.bak.tsx";
import * as $index from "./routes/index.tsx";
import * as $random from "./routes/random.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $NavButton from "./islands/NavButton.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.bak.tsx": $index_bak,
    "./routes/index.tsx": $index,
    "./routes/random.tsx": $random,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/NavButton.tsx": $NavButton,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
